@startuml

class Prenda {
    tipoDePrenda
    colorPrincipal
    colorSecundario
    material
    esBorrador

    guardarPrenda()
    guardarBorrador()
    primerPaso(tipoDePrenda)
    segundoPaso(material, color1, color2)
}

class TipoDePrenda {
    tipo
    categoria
}

enum Tipo {
    ZAPATOS
    CAMISA_MANGA_CORTA
    PANTALON
}

enum Categoria {
    PARTE_SUPERIOR,
    CALZADO,
    PARTE_INFERIOR,
    ACCESORIOS
}

class Material {
    tela
    trama
}

enum Tela {
    CUERO
    JEAN
}

enum Trama {
    LISA,
    RAYADA,
    LUNARES,
    CUADROS,
    ESTAMPADA
}

Prenda --> TipoDePrenda
Prenda --> Material

Material --> Tela
Material --> Trama

TipoDePrenda --> Tipo
TipoDePrenda --> Categoria


'============= UNIFORME ===============
class Uniforme {
    superior
    inferior
    calzado
    institucion

    Uniforme(superior, inferior, calzado, institucion)
}

class Usuario {
    obtenerSugerencia()
}

Uniforme <.. Prenda
Usuario <.. Uniforme
@enduml